background                = "#080b0d"
background-alpha          = 0.96
text                      = "#c3cbce"
border                    = "hyprland.active-border"
border-alpha              = 1.0
scrim                     = "#040507"
scrim-alpha               = 0.58
selected-background       = "#c7423c"
selected-background-alpha = 0.15
selected-text             = "#e6edee"
selected-border           = "#c7423c"
selected-border-alpha     = 0.40
